server:
  port: 8081

gg:
  jte:
    template-location: src/main/jte
    development-mode: true

spring:
  liquibase:
    enabled: false

  application:
    name: m-crm

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE