spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

  sql:
    init:
      mode: always