spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false  # убери это при использовании Liquibase

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  sql:
    init:
      mode: never  # Liquibase управляет схемой вместо schema.sql